version: "3.9"
services:
      zookeeper:
        image: confluentinc/cp-zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181

      kafka:
        image: confluentinc/cp-kafka
        ports:
          - "9092:9092"
        environment:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.73:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
          KAFKA_BROKER_ID: 1
          KAFKA_MIN_INSYNC_REPLICAS: 1

      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - "1433:1433"
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: 123Aa321
          MSSQL_PID: Developer
          MSSQL_AGENT_ENABLED: "true"

      connector:
        image: debezium/connect:1.2
        ports:
          - "8083:8083"
        environment:
          GROUP_ID: 1
          CONFIG_STORAGE_TOPIC: my_connect_configs
          OFFSET_STORAGE_TOPIC: my_connect_offsets
          STATUS_STORAGE_TOPIC: my_connect_statuses
          BOOTSTRAP_SERVERS: 192.168.0.73:9092
        depends_on:
          - sqlserver
          - kafka

      kafdrop:
        image: obsidiandynamics/kafdrop:latest
        depends_on:
          - kafka
        ports:
          - "9005:9000"
        environment:
          KAFKA_BROKERCONNECT: 192.168.0.73:9092,192.168.0.73:9092
          JVM_OPTS: "-Xms32M -Xmx64M" 
          SERVER_SERVLET_CONTEXTPATH: "/"
        depends_on:
          - kafka


